-- liquibase formatted sql

-- changeset liquibase:1

CREATE TABLE IF NOT EXISTS USER (
    USERNAME VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    FIRSTNAME VARCHAR(200) NOT NULL,
    LASTNAME VARCHAR(200) NOT NULL,
    PRIMARY KEY (USERNAME)
);
--rollback DROP TABLE USER

CREATE TABLE IF NOT EXISTS USER_ROLE (
    USERNAME VARCHAR(200) NOT NULL,
    ROLE VARCHAR(200) NOT NULL
);
--rollback DROP TABLE USER_ROLE

CREATE TABLE IF NOT EXISTS CITY (
  ID INT NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  PHOTO VARCHAR(1000),
  PRIMARY KEY (ID)
);
--rollback DROP TABLE CITY
